# Secretsの参照
name: Secrets
on: push
jobs: 
    print:
        runs-on: ubuntu-latest
        env: 
            SAMPLE_LOGIN_PASSWORD: ${{ secrets.SAMPLE_LOGIN_PASSWORD}}
        steps:
            - run: echo "${SAMPLE_LOGIN_PASSWORD}"
            - run: echo "${SAMPLE_LOGIN_PASSWORD:0:1} ${SAMPLE_LOGIN_PASSWORD?}" # ${SAMPLE_LOGIN_PASSWORD?}"は、マスクされる